### ISSUE TITLE
Java examples: AnnotateText throws FileNotFoundException

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ncbo_rest_sample_code#5]
Executing the main method in AnnotateText.java throws the following exception:

```
java.io.FileNotFoundException: http://data.bioontology.org/ontologies/OHMI/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_1909
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at AnnotateText.get(AnnotateText.java:97)
	at AnnotateText.printAnnotations(AnnotateText.java:50)
	at AnnotateText.main(AnnotateText.java:27)
Class details
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.StringReader@6cd8737; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:2836)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2778)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1659)
	at AnnotateText.jsonToNode(AnnotateText.java:75)
	at AnnotateText.printAnnotations(AnnotateText.java:50)
	at AnnotateText.main(AnnotateText.java:27)
Exception in thread "main" java.lang.NullPointerException
	at AnnotateText.printAnnotations(AnnotateText.java:52)
	at AnnotateText.main(AnnotateText.java:27)
```

**Comment by jvendetti** [comment]
The exception is thrown when the code encounters a particular class in the set of annotated classes returned for which the "self" link is invalid. Screen shot of the offending class:

![screenshot 2017-09-19 17 06 26](https://user-images.githubusercontent.com/1696923/30621549-987419c0-9d60-11e7-8978-52480f656963.png)

Issuing the [REST call](http://data.bioontology.org/ontologies/OHMI/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_1909) for the "self" link results in the following 404 response:

```
"Resource 'http://purl.obolibrary.org/obo/DOID_1909' not found in ontology OHMI submission 5"
```

According to @mdorf, we need to regenerate BioPortal's annotator cache. There is currently no mechanism in the code that deletes class data from the annotator cache when a class that existed in previous submissions is removed in the latest submission of any given ontology.

**Comment by jvendetti** [comment]
This issue was reported again today (identical exception) by @juanlossio.

The annotator cache should be regenerated because Annotator result sets contain annotatedClass objects for which the "self" link is invalid. To observe this behavior, [issue the example call](http://data.bioontology.org/annotator?text=Melanoma+is+a+malignant+tumor+of+melanocytes+which+are+found+predominantly+in+skin+but+also+in+the+bowel+and+the+eye.) to the Annotator that's provided in our REST API documentation. The first result is this annotatedClass:

![Screenshot 2019-09-27 16 50 21](https://user-images.githubusercontent.com/1696923/65808233-e7d60000-e147-11e9-85c5-b2de8b0d2e9b.png)

Issuing a [REST call](http://data.bioontology.org/ontologies/CHEAR/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3224) for the "self" link results in a 404:

```
"Resource 'http://purl.obolibrary.org/obo/NCIT_C3224' not found in ontology CHEAR submission 15"
```
